CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    DOB DATE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMP
);

CREATE TABLE PHOTOS(
    ID SERIAL PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    URL TEXT NOT NULL,
    CAPTION TEXT,
    USER_ID INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_PHOTO_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE COMMENTS(
    ID SERIAL PRIMARY KEY NOT NULL,
    MESSAGE TEXT NOT NULL,
    USER_ID INT NOT NULL,
    PHOTO_ID INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_COMMENTS_PHOTO_ID FOREIGN KEY (PHOTO_ID) REFERENCES PHOTOS(ID),
    CONSTRAINT FK_COMMENTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE SOCIAL_MEDIAS(
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    URL TEXT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_SOCIAL_MEDIAS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);